name: test

on: [push, workflow_dispatch]

jobs:
  test-lua:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: leafo/gh-actions-lua@v8
      - uses: leafo/gh-actions-luarocks@v4
      - name: Setup dependencies
        run: |
          luarocks install busted
      - name: test
          make test-lua

  test-vader:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        neovim: [false, true]
        version: [stable]

      fail-fast: false

    steps:
      - uses: actions/checkout@v1
      - name: checkout vader.vim
        uses: actions/checkout@v2
        with:
          repository: junegunn/vader.vim
          path: ./build/vim/plugins/vader.vim
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: ${{ matrix.neovim }}
          version: ${{ matrix.version }}
      - name: test
        env:
          VIM_COMMAND: ${{ steps.vim.outputs.executable }}
        run: |
          echo $VIM_COMMAND
          make test-vader
